### ISSUE TITLE
No provider for NgControl

### ISSUE THREAD

**Issue by azulay7** [mezoistvan/ng2-flatpickr#16]
Unhandled Promise rejection: Template parse errors:
No provider for NgControl ("
  </div>

    [ERROR ->]<ng2-flatpickr [config]="exampleOptions" formControlName="formControlName"></ng2-flatpickr>

  </di"): GeoSearchComponent@39:4 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
No provider for NgControl ("
  </div>

    [ERROR ->]<ng2-flatpickr [config]="exampleOptions" formControlName="formControlName"></ng2-flatpickr>

  </di"): GeoSearchComponent@39:4
    at TemplateParser.parse (http://localhost:4200/main.bundle.js:57046:19)
    at RuntimeCompiler._compileTemplate (http://localhost:4200/main.bundle.js:83418:51)
    at http://localhost:4200/main.bundle.js:83323:83
    at Set.forEach (native)
    at compile (http://localhost:4200/main.bundle.js:83323:47)
    at ZoneDelegate.invoke (http://localhost:4200/main.bundle.js:153953:26)
    at Zone.run (http://localhost:4200/main.bundle.js:153835:43)
    at http://localhost:4200/main.bundle.js:154223:57
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:153986:35)
    at Zone.runTask (http://localhost:4200/main.bundle.js:153875:47) Error: Template parse errors:
No provider for NgControl ("
  </div>

    [ERROR ->]<ng2-flatpickr [config]="exampleOptions" formControlName="formControlName"></ng2-flatpickr>

  </di"): GeoSearchComponent@39:4
    at TemplateParser.parse (http://localhost:4200/main.bundle.js:57046:19)
    at RuntimeCompiler._compileTemplate (http://localhost:4200/main.bundle.js:83418:51)
    at http://localhost:4200/main.bundle.js:83323:83
    at Set.forEach (native)
    at compile (http://localhost:4200/main.bundle.js:83323:47)
    at ZoneDelegate.invoke (http://localhost:4200/main.bundle.js:153953:26)
    at Zone.run (http://localhost:4200/main.bundle.js:153835:43)
    at http://localhost:4200/main.bundle.js:154223:57
    at ZoneDelegate.invokeTask (http://localhost:4200/main.bundle.js:153986:35)
    at Zone.runTask (http://localhost:4200/main.bundle.js:153875:47)

**Comment by kogden** [comment]
Well don't leave us hanging, what was the solution?

**Comment by azulay7** [comment]
@kogden sorry dude I don't recall. try to check if import the module, or maybe yor angular version

**Comment by cooljeffro** [comment]
Set the "name" property (instead of "formControlName") on the <ng2-flatpickr> element.

Documentation is not very clear on this point.
