### ISSUE TITLE
Error while building 

### ISSUE THREAD

**Issue by Micheal-Prisila-Fernando** [mezoistvan/ng2-flatpickr#79]
ERROR in ./node_modules/ng2-flatpickr/fesm5/ng2-flatpickr.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/home/aditya/Integra/flangetrak-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/home/aditya/Integra/flangetrak-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/home/aditya/Integra/flangetrak-app/node_modules/typescript/lib/typescript.js:16144:30)
    at Object.forEachChild (/home/aditya/Integra/flangetrak-app/node_modules/typescript/lib/typescript.js:16370:24)
    at checkNodeForDecorators (/home/aditya/Integra/flangetrak-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/aditya/Integra/flangetrak-app/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/home/aditya/Integra/flangetrak-app/node_modules/typescript/lib/typescript.js:16265:21)
    at checkNodeForDecorators (/home/aditya/Integra/flangetrak-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/aditya/Integra/flangetrak-app/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/home/aditya/Integra/flangetrak-app/node_modules/typescript/lib/typescript.js:16322:24)
    at checkNodeForDecorators (/home/aditya/Integra/flangetrak-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/aditya/Integra/flangetrak-app/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/home/aditya/Integra/flangetrak-app/node_modules/typescript/lib/typescript.js:16333:24)
    at checkNodeForDecorators (/home/aditya/Integra/flangetrak-app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/home/aditya/Integra/flangetrak-app/node_modules/typescript/lib/typescript.js:16135:24)
    at Object.forEachChild (/home/aditya/Integra/flangetrak-app/node_modules/typescript/lib/typescript.js:16229:21)

**Comment by mezoistvan** [comment]
Please check with the latest version, and resubmit this issue with the proper bug report. Thanks!

**Comment by rlaurente** [comment]
Still having this error in version 9.
